### PR TITLE
Modify validation to occur after dumping the object a serializable form

### PR DESCRIPTION
**Pull request by brockhaywood**
I'd like to also set a global or something to indicate if validation should occur and then pass that to marshall.

Maybe it should be set on a per handler registry basis and overridable per handler?

### CODE REVIEW

**Review by airstandley — APPROVED** [review]
LGTM
Though I think we'll want to bubble up the `validate` option to be something you can set/configure on the `rebar` object.

**Comment by brockhaywood** [comment]
> LGTM
> Though I think we'll want to bubble up the `validate` option to be something you can set/configure on the `rebar` object.

Agreed. Thinking about tackling that in a follow up PR since this is what's needed to unblock further testing of rebar 2.X

**Comment by airstandley** [comment]
> Maybe it should be set on a per handler registry basis and overridable per handler?

Sounds good. Though I'm not sure if it needs to be overridable per handler, or just overridable globally.

Something like:
global configuration can be 'validate', 'don't validate', or 'default -> uses handler setting'
handler configuration can be 'validate', 'don't validate', default is 'validate' to preserver existing behaviour

**Comment by brockhaywood** [comment]
> > Maybe it should be set on a per handler registry basis and overridable per handler?
> 
> Sounds good. Though I'm not sure if it needs to be overridable per handler, or just overridable globally.
> 
> Something like:
> global configuration can be 'validate', 'don't validate', or 'default -> uses handler setting'
> handler configuration can be 'validate', 'don't validate', default is 'validate' to preserve existing behaviour

yeah, im not sure either. i was thinking similar to default headers checking behavior which is configurable globally and per handler

**Pull request merged**
