### PR TITLE
add missing runtime dependencies

### PR DESCRIPTION
**Pull request by vkunz**
hi,

flask-rebar uses bits from dependent modules without declaring the proper dependency.

Full disclosure: I am not super fluent in python, so this might not be the python way of fixing this.

Only commit f73264ea5cf95865de439eb9f9a9441b921090c0 is strictly necessary, everything else should be considered rfc.

I started a fresh flask/flask-rebar project. Running the built-in development server of flask complained about imports from missing modules.

BR,
Valentin

### CODE REVIEW

**Review by VerinaG — COMMENTED** [review]
LGTM. @nlawrence22 any concerns?

**Comment by nlawrence22** [comment]
@vkunz -- Sorry for the delayed response, thanks for the contribution, we really appreciate it!  Your changes look good to me, but unfortunately It looks like tests are failing for issues unrelated to your changes -- I'd like for us to fix those underlying issues and ensure that those tests pass, and then rebase your changes on top of those fixes and make sure they pass those tests as well, if that's ok with you?  

We should be able to get those fixes in by (and likely on) Friday, March 26th Pacific Standard Time.

**Comment by vkunz** [comment]
> @vkunz -- Sorry for the delayed response, thanks for the contribution, we really appreciate it! 

no worries

>Your changes look good to me, but unfortunately It looks like tests are failing for issues unrelated to your changes -- I'd like for us to fix those underlying issues and ensure that those tests pass, and then rebase your changes on top of those fixes and make sure they pass those tests as well, if that's ok with you?

sure, that's okay

> 
> We should be able to get those fixes in by (and likely on) Friday, March 26th Pacific Standard Time.

I have a locally working fix [here](https://github.com/vkunz/flask-rebar/tree/dep-versions) I could submit but only if you'd like me to.

I wouldn't want to step on anybodies toes.

BR,
Valentin

**Review by VerinaG — APPROVED** [review]

**Comment by nlawrence22** [comment]
@vkunz -- thanks for offering a second fix!  No worries about stepping on any toes, contributions are always welcome.

It looks like Verina was able to get those changes in already, and your changes are now passing, so we'll go ahead and merge this PR.  Thank you again for the contribution!

**Pull request merged**
