### PR TITLE
Bump v2.0.0

### PR DESCRIPTION
**Pull request by brockhaywood**

### CODE REVIEW

**Comment by brockhaywood** [comment]
@barakalon seems to me the marshmallow 3 updates are worthy of a major bump? thoughts?

**Comment by barakalon** [comment]
There _shouldn't_ be any backwards incompatible changes (let me know if you're aware of one?), so I would assume a minor change.

**Comment by brockhaywood** [comment]
no, i'm not aware of any. just based on marshmallow 3 being a major version bump, this could be. but, i'm ok with a minor bump since there is nothing backwards incompatible for us.

**Comment by twosigmajab** [comment]
This is tricky because the dependency declaration already declared support for `marshmallow>=2` even though it only supported `marshmallow>=2,<3`. If it had declared that, then this PR would include the change `marshmallow>=2,<4`, and in so doing, would warrant a major version bump.

**Pull request closed without merging**
