### PR TITLE
Fixes for oneof on _flatten

### LINKED ISSUE #181: Definition lost on swagger_generator for one_of schemas.
The bug consists in the fact that in the `_flatten` function, the updated schema is only updated on the definitions when the type=object.  Here: https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/swagger_generation/generator_utils.py#L134

That `if sw.title in schema:` block should be applied for all the cases (including `elif subschema_keyword:`, and for arrays as well).

This bug also happens on flask-rebar v2, but I don't know if it's being maintained.

### PR DESCRIPTION
**Pull request by fcr--**
This would fix #181

### CODE REVIEW

**Comment by fcr--** [comment]
All right, I added a test case and fixed the one with arrays.

**Comment by fcr--** [comment]
@barakalon Would it be possible to do a release after merging this PR?

**Comment by barakalon** [comment]
I don't have permissions to do a release.
Maybe @PratikPramanik does? Or @RookieRick ?

**Comment by RookieRick** [comment]
@fcr-- I did a patch release last night that should include this (and a couple other recents PRs).  Let me know if any issues! Thanks!!

**Pull request merged**
