### PR TITLE
drop Flask-Testing dependency for testing

### LINKED ISSUE #166: pin werkzeug <1.0
Werkzeug, a sub-dependency of flask, released a major version 1.0.0 today:
https://pypi.org/project/Werkzeug/#history

This is breaking a few things on some of our builds. Looks like Flask does not pin a major version of werkzeug:
https://github.com/pallets/flask/blob/master/setup.py#L56

There is some discussion in the flask discord about it but no issues or discussion of a resolution yet
https://discordapp.com/channels/531221516914917387/531221866145251366

Can we pin `werkzeug^=0.16` in rebar for now?

### PR DESCRIPTION
**Pull request by gtmanfred**
Flask-Testing is broken with Werkzeug 1.0.0.  It also appears that a
patch was made for Flask-Testing 4 months ago, and hasn't been merged,
so it should probably be considered unmaintained.
    
Since we are using pytest anyway, we can just provide our own app
fixture for testing and just use that.

Fixes #166

### CODE REVIEW

**Comment by airstandley** [comment]
@gtmanfred Do we need to add the pytest-flask dependency? I'm fairly certain we should be able to remove the requirement without replacing it with another dependency since we aren't really relying on any of the features beyond a fixture app creation.

**Comment by gtmanfred** [comment]
I would be down to remove the dependency all together.  It is a small enough change to just make the fixture ourselves and use the test client.

**Comment by gtmanfred** [comment]
Yup, looks like it should already work, just straight up dropping that dependency.

**Comment by airstandley** [comment]
Sweet. In that case can we split this into two separate issues, removing the dependency and "pytestifing" the tests?

(I know I'm in a tiny minority here, but I really don't like pytest's RTI fixtures. Gives me flashbacks to  nightmares with DUnitX.)

**Comment by gtmanfred** [comment]
I would rather not split that. The only tests that I pytestified are the ones that use fixtures, because I wanted to avoid mixing the fixture + self arguments.

**Comment by airstandley** [comment]
Split out the changes needed to drop Flask-Testing #173

**Comment by airstandley** [comment]
@gtmanfred FWIW I think you great work here "pytestifying" our tests if we want to move in that direction.

**Comment by gtmanfred** [comment]
:+1: no worries I just didn't want to split it out.

Also, you are probably going to need to grab the changes to .travis.yml to get the tests to pass.

And the JSONResponse changes because flask < 1.0.0 does not have .json on the response object.

**Pull request closed without merging**
