### PR TITLE
Treat "description" key the same way as "explode" key for query and h…

### PR DESCRIPTION
**Pull request by artreven**
…eader parameters

See issue #128 .

### CODE REVIEW

**Comment by brockhaywood** [comment]
@RookieRick Sending this your way. I'm not nearly as familiar with what level of support we have for which versions of openapi.

**Comment by RookieRick** [comment]
> Awesome! Thanks for doing this.
> 
> Is it possible to add a test for this change?

+1 to this, we'll want to add a test case to ensure the generated Swagger matches expectation - @arteven if you can add that, that would be great - if needed though I can prob throw something together for that, just let me know.  And thanks for the contribution!!

**Comment by airstandley** [comment]
It might be worth making a more general method to handle bumping up a list of properties from the `jsonschema` to the `parameter`.

Looking over the 2.0/3.0.2 differences if we ever added support for any of the following fields, then I think they would also want to be "bumped up a level".
v2 & v3: allowEmptyValues
v3 only: deprecated, allowReserved, example, examples

**Comment by artreven** [comment]
Thanks for the feedback. I have modified an existing test "exploded_query_string" to include the description of parameters. Not sure if it is the right way, though, please, have a look.

I am new to gitchangelog. It has output some strange message "Revision '^v1.10.0' is not valid.". Please, also have a look if everything is fine with the changelog.

**Comment by RookieRick** [comment]
> Thanks for the feedback. I have modified an existing test "exploded_query_string" to include the description of parameters. Not sure if it is the right way, though, please, have a look.
> 
> I am new to gitchangelog. It has output some strange message "Revision '^v1.10.0' is not valid.". Please, also have a look if everything is fine with the changelog.

Thanks!  No worries on the version thing - that was a result of a typo'd version number on my part.  I'll take care of that and changelog at same time :)

**Pull request merged**
